# Generated by Django 2.2 on 2020-01-29 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0004_auto_20200128_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=75)),
                ('company', models.CharField(max_length=75)),
                ('applyDate', models.DateField()),
                ('respondDate', models.DateField()),
                ('response', models.BooleanField()),
                ('estSalary', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cozyfolio_app.Portfolio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cozyfolio_app.User')),
            ],
        ),
    ]
