# Generated by Django 2.2 on 2020-01-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0005_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cozyfolio_app.Portfolio'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cozyfolio_app.User'),
        ),
    ]
