# Generated by Django 2.2 on 2020-01-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0007_auto_20200129_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='offertReceived',
            new_name='offerReceived',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='offertReject',
            new_name='offerReject',
        ),
    ]
