# Generated by Django 2.2 on 2020-01-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0009_auto_20200129_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='offerReject',
            field=models.BooleanField(null=True),
        ),
    ]
