# Generated by Django 2.2 on 2020-01-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0011_auto_20200130_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='picImage',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='user',
            name='tagLine',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, upload_to='settmedia/'),
        ),
    ]
