# Generated by Django 2.2 on 2020-01-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0012_auto_20200130_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=models.ImageField(null=True, upload_to='headshot/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
